[package]
name = "api"
edition.workspace = true
version.workspace = true
readme.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true

[dependencies]
core.path = "../core"

serde.workspace = true

[lints]
workspace = true
